version: '2'

services:
  todo-app:
    image: 'todo-app:v1'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_PROFILE: test
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true